# Generated by Django 4.2.1 on 2023-11-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("women", "0009_husband_women_husband"),
    ]

    operations = [
        migrations.AddField(
            model_name="husband",
            name="m_count",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
